[package]
name = "restate-web-ui"
description = "Rust wrapper for Facebook's RocksDB embeddable database"
publish = false
edition = "2021"
version = "0.0.82"

[dependencies]
include_dir = "0.7.4"

[build-dependencies]
anyhow = "1.0.68"
zip = { version = "3.0" }

